#!/usr/bin/env python3
"""Build the DocuSign API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Connected Fields': 'Connected Fields',
}

LINES = [
    {
        "name": 'DocuSign Core',
        "color": '#FFCB00',
        "stations": [
        ('eSignature', (270, 200)),
        ('Admin', (430, 175)),
        ('Click', (590, 165)),
        ('Maestro', (750, 175)),
        ('Monitor', (910, 200)),
        ],
    },
    {
        "name": 'Forms & Workflows',
        "color": '#1E5BD0',
        "stations": [
        ('Rooms', (270, 320)),
        ('Web Forms', (440, 295)),
        ('Notary', (610, 295)),
        ('Navigator', (780, 295)),
        ],
    },
    {
        "name": 'Specialized',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Workspaces', (810, 470)),
        ('CLM', (910, 555)),
        ('Connected Fields', (710, 555)),
        ],
    },
]

URL_OVERRIDES = {
    'eSignature': 'https://apis.apis.io/apis/docusign/docusign-api/',
    'Admin': 'https://apis.apis.io/apis/docusign/docusign-admin-api/',
    'Click': 'https://apis.apis.io/apis/docusign/docusign-click-api/',
    'Maestro': 'https://apis.apis.io/apis/docusign/docusign-maestro-api/',
    'Monitor': 'https://apis.apis.io/apis/docusign/docusign-monitor-api/',
    'Rooms': 'https://apis.apis.io/apis/docusign/docusign-rooms-api/',
    'Web Forms': 'https://apis.apis.io/apis/docusign/docusign-web-forms-api/',
    'Notary': 'https://apis.apis.io/apis/docusign/docusign-notary-api/',
    'Navigator': 'https://apis.apis.io/apis/docusign/docusign-navigator-api/',
    'Workspaces': 'https://apis.apis.io/apis/docusign/docusign-workspaces-api/',
    'CLM': 'https://apis.apis.io/apis/docusign/docusign-clm-api/',
    'Connected Fields': 'https://apis.apis.io/apis/docusign/docusign-connected-fields-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The DocuSign API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: docusign/openapi · github.com/api-evangelist/docusign',
        out_dir=Path(__file__).resolve().parent,
        out_basename='docusign-subway-map',
        provider_id='docusign',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
