openapi: 3.0.1
info:
  title: DocuSign Admin AccountBrands MultiProductUserManagement API
  description: An API for an organization administrator to manage organizations, accounts and users
  termsOfService: https://www.docusign.com/company/terms-and-conditions/developers
  contact:
    name: DocuSign Developer Center
    url: https://developers.docusign.com
    email: devcenter@docusign.com
  version: v2.1
servers:
- url: https://api.docusign.net/Management
tags:
- name: MultiProductUserManagement
  description: Methods to manage multi-product users in an account.
paths:
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups:
    get:
      tags:
      - MultiProductUserManagement
      summary: Docusign Returns a list of DSGroups.
      description: 'Returns a list of DSGroups


        - Required scopes: `user_read`'
      operationId: DocuSignGroupsv21_GetDSGroups_V2_1
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getDSGroups
      x-ds-method: getDSGroups
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    post:
      tags:
      - MultiProductUserManagement
      summary: Docusign Creates a new DSGroup.
      description: 'Creates a new DSGroup.


        - Required scopes: `user_write`'
      operationId: DocuSignGroupsv21_AddDSGroup_V2_1
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addDSGroup
      x-ds-method: addDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}:
    get:
      tags:
      - MultiProductUserManagement
      summary: Docusign Returns details about a single DSGroup.
      description: 'Returns details about a single DSGroup.


        - Required scopes: `user_read`'
      operationId: DocuSignGroupsv21_GetDSGroup_V2_1
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getDSGroup
      x-ds-method: getDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    delete:
      tags:
      - MultiProductUserManagement
      summary: Docusign Deletes a DSGroup.
      description: 'Deletes a DSGroup


        - Required scopes: `user_write`'
      operationId: DocuSignGroupsv21_DeleteDSGroup_V2_1
      security:
      - accessCode:
        - user_write
      x-ds-methodname: deleteDSGroup
      x-ds-method: deleteDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}/users:
    get:
      tags:
      - MultiProductUserManagement
      summary: Docusign Gets a list of users in a DSGroup.
      description: 'Gets a list of users in a DSGroup.


        - Required scopes: `user_read`'
      operationId: DocuSignGroupsv21_GetDSGroupUsers_V2_1
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getDSGroupUsers
      x-ds-method: getDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    post:
      tags:
      - MultiProductUserManagement
      summary: Docusign Adds a list of users to a DSGroup.
      description: 'Adds a list of users to a DSGroup.


        - Required scopes: `user_write`'
      operationId: DocuSignGroupsv21_AddDSGroupUsers_V2_1
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addDSGroupUsers
      x-ds-method: addDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    delete:
      tags:
      - MultiProductUserManagement
      summary: Docusign Removes a list of users from a DSGroup.
      description: 'Removes a list of users from a DSGroup.


        - Required scopes: `user_write`'
      operationId: DocuSignGroupsv21_RemoveDSGroupUsers_V2_1
      security:
      - accessCode:
        - user_write
      x-ds-methodname: removeDSGroupUsers
      x-ds-method: removeDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/products/permission_profiles:
    get:
      tags:
      - MultiProductUserManagement
      summary: Docusign Gets products associated with the account and the available permission profiles.
      description: 'Gets products associated with the account and the available permission profiles.


        - Required scopes: `user_read`'
      operationId: OrganizationProductPermissionProfile_GetProductPermissionProfiles
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getProductPermissionProfiles
      x-ds-method: getProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/products/users/{userId}/permission_profiles:
    get:
      tags:
      - MultiProductUserManagement
      summary: Docusign Retrieves a list of user's permission profiles for each account's product.
      description: 'Retrieves a list of user''s permission profiles for each account''s product.


        - Required scopes: `user_read`'
      operationId: OrganizationProductPermissionProfile_GetUserProductPermissionProfiles
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getUserProductPermissionProfiles
      x-ds-method: getUserProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
    post:
      tags:
      - MultiProductUserManagement
      summary: Docusign Assigns user to permission profiles for one or more products.
      description: 'Assigns user to permission profiles for one or more products.


        - Required scopes: `user_write`'
      operationId: OrganizationProductPermissionProfile_PostUserProductPermissionProfiles
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addUserProductPermissionProfiles
      x-ds-method: addUserProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/users:
    post:
      tags:
      - MultiProductUserManagement
      summary: Docusign Creates and updates a multi-product user.
      description: 'Creates and updates a multi-product user.


        - Required scopes: `user_write`'
      operationId: OrganizationUser_OrganizationUsers_PostAccountUsersV2_1
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addOrUpdateUser
      x-ds-method: addOrUpdateUser
      x-ds-service: Users
      x-ds-in-sdk: true
components:
  securitySchemes:
    accessCode:
      type: oauth2
      description: OAuth2 Access code Grant
      flows:
        authorizationCode:
          authorizationUrl: https://account.docusign.com/oauth/auth
          tokenUrl: https://account.docusign.com/oauth/auth
          scopes:
            organization_read: ''
            permission_read: ''
            group_read: ''
            user_read: ''
            account_read: ''
            account_write: ''
            user_write: ''
            identity_provider_read: ''
            domain_read: ''
x-ds-categories:
- name: UserManagement
  summary: Methods to manage users in an account.
  description: Methods to manage users in an account.
- name: BulkOperations
  summary: Methods to import and export users and accounts.
  description: Methods to import and export users and accounts.
- name: IdentityProviders
  summary: Methods to get a list of identity providers.
  description: Methods to get a list of identity providers.
- name: ReservedDomains
  summary: Methods to get a list of reserved domains.
  description: Methods to get a list of reserved domains.
- name: Organization
  summary: Methods for working with organizations.
  description: Methods for working with organizations.
x-original-swagger-version: '2.0'
